data:
  name: poloclub/diffusiondb
  split: train
  min_buffer: 100
  max_buffer: 1000
  resize_base: 256
  crop_size: 224
  image_key: image
model:
  capacity: 4
  num_layers: 3
  input_channels: 3
  output_channels: 1
  kernel_size: 3
train:
  device: auto
  batch_size: 16
  num_workers: 0
  learning_rate: 0.001
  output_dir: output
  output_log_interval: 100
